### PR TITLE
Added prop for disabling default tvOS view animation on RCT View and updated RCT Navigator to remove menu gesture recognizer on base view 

### PR DESCRIPTION
**Pull request by kgowru**
**Motivation**
- disableParallax: create prop type that disables tvOS animation on RCT View. The default is set to false.
- support for menu button press to return back to home: code written in RCT Navigator that checks to see if the current screen is on the bottom of the stack. If so, it removes the menu type recognizer so that tvOS can detect it and return the user to the home screen when clicked.

**Test plan (required)**
None

### CODE REVIEW

**Comment by kgowru** [comment]
@douglowder Just merge

**Comment by kgowru** [comment]
@douglowder Just merged with your master branch and added preprocessor tags for tvOS in RCTNavigator.m. Let me know if anything else needs to be done here.

**Comment by douglowder** [comment]
Kapil, can you merge my upstream changes to your repo again, and then I'll merge this pull request to my repo today.

**Comment by kgowru** [comment]
@douglowder Done! Let me know if there's anything missing. I believe I merged properly.

**Pull request merged**
